'''
Created on Dec 14, 2012

@author: marek
INTEGRACNE TESTY
'''

import unittest
import datetime

from sk.marek.barak.app.DatabaseLoader import *



class TestZamestnanecLoader(unittest.TestCase):
    @unittest.skip("Already tested for new DB")
    def testZamLoad(self):
        print "Zam loader test"
        dbLoader = Dim_ZamestanecLoader()
        l = list()
        l.append("Marek")
        l.append("Barak")
        l.append("Programator")
        l.append(1)
        l.append("mrk.barak@gmail.com")
        rows = list()
        s=list()
        s.append("Jaroslav")
        s.append("Hoblak")
        s.append("Ozran")
        s.append(1)
        s.append("jaroslav.hoblak@gmail.com")
        rows.append(l)
        rows.append(s)
        dbLoader.load(rows)
        print dbLoader.getKey()
        
    @unittest.skip("Tested on new DB")
    def testDodLoader(self):
        print "Dod loader test"
        dbLoader = Dim_DodavatelLoader()
        l = list()
        l.append("Prvy")
        l.append("Prve miesto")
        l.append("123456789/4587")
        l.append("12345678")
        l.append("1234567891")
        s = list()
        s.append("Second")
        s.append("Druhe miesto")
        s.append("987654321/3216")
        s.append("98765432")
        s.append("1234567801")
        row = list()
        row.append(l)
        row.append(s)
        dbLoader.load(row)
        
    @unittest.skip("Already tested for new DB")
    def testCasLoad(self):
        print "CAS load Test"
        dbLoad = Dim_CasLoader()
        tm = datetime.datetime.now()
        tm.weekday()
        l = list()
        tm += datetime.timedelta(days = 1)
        l.append(tm)
        l.append(tm.year)
        l.append(tm.month)
        l.append(tm.day)
        l.append("Sobota")
        row = list()
        row.append(l)
        dbLoad.load(row)
        
    @unittest.skip("Already tested for new DB")
    def testTovarLoader(self):
        dbLoader = DimTovarLoader()
        l = list()
        l.append("Kategoria Horor")
        l.append("Nazov T Kniha")
        l.append("Platforma 1")
        l.append("Mutacia CZE")
        l.append(600)
        l.append(datetime.datetime.now())
        l.append("Marek Barak")
        l.append("Slov art")
        l.append("Volaco hlupeho")
        l.append("Prve ISBN")
        l.append(1525.5)
        l.append(18)
        row = list();
        row.append(l)
        s= list(l)
        row.append(s)
        dbLoader.load(row)
        
    @unittest.skip("Already tested for new DB")
    def testZakaznikLoader(self):
        l = list()
        l.append("s.r.o")
        l.append("Vydaj sro")
        l.append("Kovacova 21")
        l.append("Namestovo")
        l.append("Okres")
        l.append("KRAJ")
        l.append("0915126544")
        l.append("vydaj@zmrd.sk")
        l.append("123554478/8547")
        l.append("12345678")
        l.append("1234567891")
        s = list(l)
        row = list()
        row.append(l)
        row.append(s)
        dbLoader = DimZakaznikLoader()
        dbLoader.load(row)
        
    @unittest.skip("Already tested on new DB")
    def testPobockaLoader(self):
        l = list()
        l.append("Nove Zamky")
        l.append("Nitriansky")
        l.append("Nitriansky")
        l.append("Komarnanska 29")
        l.append("0915126544")
        l.append("mrk.barak@gmail.com")
        row = list()
        row.append(l)

        dbLoader = DimPobockaLoader()
        dbLoader.load(row)
        
    @unittest.skip("Already tested for new DB")
    def testFakturaLoader(self):
        l = list()
        l.append(None)
        l.append(True)
        l.append(False)
        s = list(l)
        row = list()
        row.append(l)
        row.append(s)
        dbLoader= DimFakturaLoader()
        dbLoader.load(row)
        
    @unittest.skip("Already tested on new DB")
    def testSluzbyZakaznikomLoader(self):
        l = list()
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append("Druh Otazky")
        l.append("Text Otazky")
        l.append("Text_odpovede")
        l.append(False)
        row = list()
        row.append(l)
        dbLoader = FaktSluzbyZakaznikomLoader()
        print "KEYS "
        print dbLoader.getKey()
        dbLoader.load(row)
        
    @unittest.skip("Already tested fro new DB")
    def testFaktSkladLoader(self):
        d=list()
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(30)
        d.append("dostupne")
        l=list()
        l.append(2)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(30)
        l.append("dostupne")
        row =list()
        row.append(l)
        row.append(d)
        dbLoader = FaktSkladLoader()
        dbLoader.load(row)
        
    @unittest.skip("Already tested on new DB")
    def testFaktObjednavkaLoader(self):
        d = list()
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(200)
        d.append(10)
        d.append(True)
        d.append("Blbost")
        d.append(True)
        d.append("online")
        d.append("prijata")
        l = list()
        l.append(2)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(200)
        l.append(5)
        l.append(False)
        l.append("Blbost")
        l.append(False)
        l.append("online")
        l.append("pripravena na expediciu")
        row = list()
        row.append(l)
        row.append(d)
        dbloader = FaktObjednavkaLoader()
        dbloader.load(row)
        
    @unittest.skip("Already tested fro new DB")
    def testDodavkaLoader(self):
        d= list()
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append("Poznamka 1")
        d.append(25)
        l= list()
        l.append(2)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append("Poznamka 2")
        l.append(30)
        row = list()
        row.append(l)
        row.append(d)
        dbLoader = FaktDodavkaLoader()
        dbLoader.load(row)
        
    @unittest.skip("Already tested for new DB")
    def testReklamaciaLoader(self):
        d = list()
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append(1)
        d.append("Popis chyby 1")
        d.append(True)
        d.append(True)
        d.append("Zdovodnenie 1")
        d.append(5)
        l = list()
        l.append(2)
        l.append(1)
        l.append(1)
        l.append(1)
        l.append(2)
        l.append("Popis chyby 2")
        l.append(False)
        l.append(True)
        l.append("Zdovodnenie 2")
        l.append(2)
        row = list()
        row.append(d)
        row.append(l)
        dbLoader= FaktReklamaciaLoader()
        dbLoader.load(row)
        
    @unittest.skip("Tested on new DB")    
    def testZamestnanecPobockaLoader(self):
        l = list()
        l.append(1)
        l.append(1)
        r = list()
        r.append(2)
        r.append(1)
        row = list()
        row.append(l)
        row.append(r)
        dbLoader = FaktZamestnanecPobockaLoader()
        dbLoader.load(row)
        
if __name__ == "__main__":
    #import sys;sys.argv = ['', 'Test.testName']
    unittest.main()